### ISSUE TITLE
Error notification appears after closing a tab

### ISSUE THREAD

**Issue by timothyis** [neil-orans/hyper-savetext#2]
When I close a tab, I get an error notification and this in the console:

![image](https://user-images.githubusercontent.com/1695613/39340285-229dda50-4982-11e8-8a06-d9c54e4ed36c.png)

Hyper Version: Hyper 2.1.0-canary.1 (canary)
All plugins installed:
```
  hyper-tabs-enhanced (0.4.2),
  hypercwd (1.2.2),
  hyper-savetext (1.0.1)
```
OS: macOS High Sierra

**Comment by neil-orans** [comment]
Just published [1.0.2](https://www.npmjs.com/package/hyper-savetext/v/1.0.2) which should fix this. Please let me know if you are still receiving this error.
