### ISSUE TITLE
Plugin does not work at all

### ISSUE THREAD

**Issue by Enteleform** [neil-orans/hyper-savetext#3]
> **System:**
> &nbsp; &nbsp; Windows 10.0.16299.371 Pro x64
> &nbsp; &nbsp; Hyper 2.0.0

This plugin causes the following error upon startup of Hyper:
`[Notification] Plugin error: Error occurred. Check Developer Tools for details`
but no additional information shows up in the dev console.

Also, the `Export text as...` menu option is unresponsive, and the `Export selected text as...` option remains disabled when a selection is made.

**Comment by neil-orans** [comment]
Do you have any other plugins installed? If so, what versions? I am trying to reproduce this, but it is working for me using the same exact setup as you have listed.

**Comment by Enteleform** [comment]
Tried toggling everything on & off one at a time & ran into some weird issues. Then ran `remove-node-modules` & reinstalled all plugins from scratch & it seems everything is working fine now.

**Comment by neil-orans** [comment]
Thanks for the feedback!
