### ISSUE TITLE
Won't "Export Text As" or "Export Selected Text As"

### ISSUE THREAD

**Issue by chris-c-thomas** [neil-orans/hyper-savetext#5]
So I recently came across this plugin and could have very good use for it. However it's not working for me.

MacOS 10.14.5
Hyper 3.0.2 (Stable)

**Plugins:**
<img width="262" alt="hyper-savetext-not-working-1" src="https://user-images.githubusercontent.com/22353987/59694975-13dbff80-91af-11e9-9dcc-d3e0216c2b4f.png">

<img width="380" alt="hyper-savetext-not-working-2" src="https://user-images.githubusercontent.com/22353987/59694992-18081d00-91af-11e9-9478-cf8d33a2fdfc.png">

I tried uploading a video but unfortunately not supported. Basically when I select the menu options under Shell they don't do anything.

**Comment by neil-orans** [comment]
I haven't tested this on versions of Hyper past 2.1. I'll look into this soon.

**Comment by chris-c-thomas** [comment]
@neil-orans Okay np. Let me know if there's anything I can do to help.

**Comment by neil-orans** [comment]
@chris-c-thomas Let me know if you still run into this issue with the most updated version of the plugin (version 1.1.2, pushed a few moments ago). Thanks!
